name: @plugin.name@
main: com.jacksonchen666.autolavacast.AutoLavacast
author: JacksonChen666
api-version: 1.16
version: @plugin.version@
description: Creates a lavacast on your command.

commands:
  lavacast:
    description: A template command
