name: @plugin.name@
main: com.jacksonchen666.autolavacast.AutoLavacast
author: JacksonChen666
api-version: 1.16
version: @plugin.version@
description: Creates a lavacast on your command.

commands:
  template:
    description: A template command

permissions:
  Template:
    default: not op
    children:
      Template.Template: true
  Template.Template:
    description: A template permission
